
// This file is no longer needed as we're using dynamic treemap generation
// The data is now generated by the GPT backend edge function

export const defaultResearchAreasData = [
  {
    name: "Primary Research",
    size: 40,
    fill: "#4C7CFC",
    papers: 40
  },
  {
    name: "Secondary Analysis", 
    size: 30,
    fill: "#8D84C6",
    papers: 30
  },
  {
    name: "Applications",
    size: 20,
    fill: "#A94CF7", 
    papers: 20
  },
  {
    name: "Other Areas",
    size: 10,
    fill: "#4A3D78",
    papers: 10
  }
];
