// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://ukqcklsmzajgumwfihnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrcWNrbHNtemFqZ3Vtd2ZpaG51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzM4NTIsImV4cCI6MjA2NDUwOTg1Mn0.96d3XKHF5-ZpN6tVj2PDwG89MdgQb1Sg82Ve9ekQHv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
