// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrjbxcurjbjqgwkcnnbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyamJ4Y3VyamJqcWd3a2NubmJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTk2NTMsImV4cCI6MjA2MzkzNTY1M30.5zC3H9xHSlCHBFDdHLgN4tJQ4OqgUmYdnIF6OOHBAWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);