// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnnvcyrohovytovydaig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ubnZjeXJvaG92eXRvdnlkYWlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzAzNTMsImV4cCI6MjA2NDYwNjM1M30.jIiWoBhdWJ758qlK4dx09EpNdzYBS34SqGDqU4YfU4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);